### ISSUE TITLE
Prettier support

### ISSUE THREAD

**Issue by allan2** [TechTheAwesome/code-yew-server#10]
It would be nice to support Prettier formatting eventually.

**Comment by abduelhamit** [comment]
@allan2, are you sure that it's something that this plugin has to support and not Prettier?

**Comment by ttax00** [comment]
Even so, I don't think currently Prettier can handle Yew's macro syntax?

**Comment by allan2** [comment]
@abduelhamit Elm and Svelte support is as [community plugins](https://prettier.io/docs/en/plugins.html#community-plugins).

It would be nice if the eventual code formatting supported Prettier rules, even if it doesn't use the Prettier JS engine. Of course, there would first have to be HTML formatting ;)

I did see this macro formatter this week, which might be helpful for formatting `html!`
https://github.com/andrewbaxter/genemichaels

**Comment by ttax00** [comment]
I think @abduelhamit is right, implementing a format-lint system from scratch inside this extension is too much. And it'd be better for someone else to create a prettier community plugin for the `html!` macro syntax. Instead of having this extension call prettier in a proxy way. 

> I did see this macro formatter this week, which might be helpful for formatting html!
https://github.com/andrewbaxter/genemichaels

This is more like a replacement for `rustfmt`. And since this plugin runs parallel with `rust-analyzer`, I feel like letting them handle `rustfmt` would be better. 

This will remains in the un-planned category for now.
