### ISSUE TITLE
Add a link to the vscode plugin to the yew docs

### ISSUE THREAD

**Issue by WorldSEnder** [TechTheAwesome/code-yew-server#13]
:wave: I recently became aware that this exists. Do you consider this extension stable and healthy enough to add it to the official yew docs?

Specifically, the editor setup docs, [here (for 0.20)](https://github.com/yewstack/yew/blob/master/website/versioned_docs/version-0.20/getting-started/editor-setup.mdx) and [here (for devel)](https://github.com/yewstack/yew/blob/master/website/docs/getting-started/editor-setup.mdx).

Feel free to submit a PR with a short descriptive paragraph and a link to the plugin, I'd be glad to add this to reach a wider audience ;)

**Comment by ttax00** [comment]
Hello! And I'm truly sorry for my late reply! 😶‍🌫️ 

Life has been busy for me in these few weeks, but I am glad that you decided to reach out! I had plans to do add some more features before considering a release status on marketplace.

I can add the documentations now, after refactoring at least, but the descriptions might be changing in the future 😮 since it is still a WIP.
