### ISSUE TITLE
How to use extension?

### ISSUE THREAD

**Issue by devgony** [TechTheAwesome/code-yew-server#16]
I tried to download `TechTheAwesome.rust-yew-0.1.0.vsix` file from market and added to VSCode manually.
But it seems like does not work.

Though I saw this extension is pre-released yet, Isn't there any way to use it currently?

**Comment by ttax00** [comment]
Can you give more specific to what your setup is looking like? Do you have `rust-analyzer` installed, what's your `.rs` file looks like, ... ? 
![image](https://user-images.githubusercontent.com/10691398/213879458-7ee022bd-f00b-462e-9be9-18f9b7ab90fc.png)
Do you see this on your bottom right?

**Comment by devgony** [comment]
Ohh.. i can see the `Rust Yew` button.
But no feature is working at all like html highlight, hover, completion(especially for tailwind)
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/51254761/213902139-e93ceb09-6ef6-4ee2-acca-257e91be7810.png">

**Comment by ttax00** [comment]
The syntax highlighting does seem to work, otherwise `div` & `main` won't be red. Did you try `F2` rename like how you would in React for a HTML tag? 

Also the extension don't have competition for tailwind it is from tailwind's extension. My extension only support basic HTML attributes completion. 
The way you install pre-released extension inside vscode market place is by clicking the drop down button, next to install. 
![image](https://user-images.githubusercontent.com/10691398/213902953-e5d76b1c-c11c-4f3e-93db-fef160d9c80e.png)
And hovering your mouse over main you should get this
![image](https://user-images.githubusercontent.com/10691398/213902978-571b3b5e-6607-4e08-b697-f833e69e1448.png)
Please check if you have `rust analyzer`, `HTML Language Server` & `Rust Yew Server` running.
![image](https://user-images.githubusercontent.com/10691398/213903051-b0a9ee8c-416e-4835-a7e8-d373975c776b.png)

**Comment by ttax00** [comment]
Update: version 0.2.0 has been published on [marketplace](https://marketplace.visualstudio.com/items?itemName=TechTheAwesome.rust-yew) It should be way less buggy than the pre-released version. 

Closing this issue in due of being outdated.
