### ISSUE TITLE
Ctrl + / creates html <-- --> comments that are not supported in yew

### ISSUE THREAD

**Issue by voidpumpkin** [TechTheAwesome/code-yew-server#23]
First of all, love this extension and I hope to contribute in the future. You are AWESOME!

The bug:

Given
```
    let test = html! {
        <div></div>
    };
```

If I ctrl + / on the line with the div, it will become:

```
    let test = html! {
        <!-- <div></div> -->
    };
```

Yew will not parse this:
![image](https://user-images.githubusercontent.com/32368314/230080518-edceeaee-6cd8-4125-944a-cf95b6f1051b.png)

What would be the intended IDEAL design for this?
I would assume we at yew hopefully should implement support for html comments?

**Comment by ttax00** [comment]
I think yew has gone with the default `//` rust comment as it is thrown out before the macro even get processed. Seen here in this issue: https://github.com/yewstack/yew/issues/2910

I'm not sure if this is due to the language configuration from `javascriptreact` since its the base for syntax highlighting, and vscode might pull comment config from there or it was due to some feature API i've implemented. I'll look into it when i have some more time this weekend :)

**Comment by ttax00** [comment]
### Update

I think I've solved the issue, now that `ctrl + /` will creates a `//` line comment instead of the default for html. Will merge this into main branch soon. Unless I missed something, do let me know :smile: 

![image](https://user-images.githubusercontent.com/10691398/231545708-2dfa9fdf-2a6f-4f65-a0ee-1997e28c3536.png)

**Comment by voidpumpkin** [comment]
@TechTheAwesome Looks great. Thx a lot!
I'm not sure if I will have time to test it soon, so I'll just wait when its released.
